import Link from "next/link";
import { ArrowUpRight, BadgeCheck, EyeOff, FileSearch, ShieldAlert } from "lucide-react";

const requirements = [
  ["০১", FileSearch, "নির্দিষ্ট ঘটনার তথ্য", "দফতর, সময়, সেবা ও ঘটনার বর্ণনায় পর্যাপ্ত প্রাসঙ্গিকতা থাকতে হবে।"],
  ["০২", BadgeCheck, "প্রাসঙ্গিক প্রমাণ বা উৎস", "নাম উল্লেখের আগে প্রমাণ বা প্রকাশ্য সরকারি/আদালত নথির সঙ্গে মিল দেখা হয়।"],
  ["০৩", EyeOff, "ক্ষতির ঝুঁকি পর্যালোচনা", "বাসার ঠিকানা, ফোন, পরিবার, অপ্রাসঙ্গিক ব্যক্তিগত তথ্য এবং হয়রানির ঝুঁকি বাদ দেওয়া হয়।"],
] as const;

export function PersonRecordPolicy() {
  return <div className="grid gap-6 xl:grid-cols-[minmax(0,1fr)_320px]"><section className="border border-border bg-card"><div className="border-b border-border p-5 sm:p-7"><p className="mono text-[10px] font-bold tracking-[0.16em] text-primary">DISCLOSURE THRESHOLD</p><h2 className="mt-2 text-2xl font-bold">নাম প্রকাশ একটি ব্যতিক্রম</h2><p className="mt-3 max-w-2xl text-sm leading-6 text-muted-foreground">প্রতিবেদনে কারও নাম থাকলেই তা public profile-এ দেখানো হয় না। প্রাসঙ্গিকতা, প্রমাণ এবং ক্ষতির ঝুঁকি—তিনটি বিষয় আলাদা করে দেখা হয়।</p></div><div className="divide-y divide-border">{requirements.map(([number, Icon, title, copy]) => <article key={number} className="grid gap-4 p-5 sm:grid-cols-[60px_minmax(0,1fr)] sm:p-7"><p className="display text-3xl font-bold text-primary">{number}</p><div><div className="flex items-center gap-2"><Icon className="size-4 text-primary" /><p className="text-lg font-bold">{title}</p></div><p className="mt-2 max-w-2xl text-sm leading-6 text-muted-foreground">{copy}</p></div></article>)}</div></section><aside className="space-y-5"><section className="border border-foreground bg-foreground p-6 text-background"><EyeOff className="size-6 text-secondary" /><p className="mono mt-7 text-[10px] font-bold tracking-[0.16em] text-secondary">PUBLIC PROFILE RULE</p><h2 className="mt-3 text-2xl font-bold leading-8">ব্যক্তিগত পরিচয় নয়, প্রাসঙ্গিক জবাবদিহিতা</h2><p className="mt-4 text-sm leading-6 text-background/75">এই পেজে কখনো বাসা, ফোন, NID, ব্যাংক তথ্য, পরিবার বা অন্য সংবেদনশীল তথ্য দেখানো হবে না।</p></section><section className="border border-primary/30 bg-primary/5 p-5"><ShieldAlert className="size-5 text-primary" /><h2 className="mt-3 font-bold">কোনো তথ্য ভুল হলে</h2><p className="mt-2 text-sm leading-6 text-muted-foreground">ভুল, privacy ঝুঁকি বা প্রাসঙ্গিক জবাব থাকলে সংশোধনী অনুরোধ করা যাবে।</p><Link href="/appeal" className="mt-4 inline-flex items-center gap-1 text-sm font-bold underline decoration-primary decoration-2 underline-offset-4">সংশোধনী অনুরোধ <ArrowUpRight className="size-4" /></Link></section></aside></div>;
}
